// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-toolkit/tools/environments (interfaces: ComponentFactory)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_component_factory.go -package=mock github.com/KirkDiggler/rpg-toolkit/tools/environments ComponentFactory
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockComponentFactory is a mock of ComponentFactory interface.
type MockComponentFactory struct {
	ctrl     *gomock.Controller
	recorder *MockComponentFactoryMockRecorder
	isgomock struct{}
}

// MockComponentFactoryMockRecorder is the mock recorder for MockComponentFactory.
type MockComponentFactoryMockRecorder struct {
	mock *MockComponentFactory
}

// NewMockComponentFactory creates a new mock instance.
func NewMockComponentFactory(ctrl *gomock.Controller) *MockComponentFactory {
	mock := &MockComponentFactory{ctrl: ctrl}
	mock.recorder = &MockComponentFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentFactory) EXPECT() *MockComponentFactoryMockRecorder {
	return m.recorder
}

// CreateComponent mocks base method.
func (m *MockComponentFactory) CreateComponent(spec any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComponent", spec)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComponent indicates an expected call of CreateComponent.
func (mr *MockComponentFactoryMockRecorder) CreateComponent(spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComponent", reflect.TypeOf((*MockComponentFactory)(nil).CreateComponent), spec)
}

// GetComponentType mocks base method.
func (m *MockComponentFactory) GetComponentType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetComponentType indicates an expected call of GetComponentType.
func (mr *MockComponentFactoryMockRecorder) GetComponentType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentType", reflect.TypeOf((*MockComponentFactory)(nil).GetComponentType))
}

// Validate mocks base method.
func (m *MockComponentFactory) Validate(spec any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockComponentFactoryMockRecorder) Validate(spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockComponentFactory)(nil).Validate), spec)
}
