// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-toolkit/tools/environments (interfaces: EnvironmentGenerator)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_generator.go -package=mock github.com/KirkDiggler/rpg-toolkit/tools/environments EnvironmentGenerator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	core "github.com/KirkDiggler/rpg-toolkit/core"
	environments "github.com/KirkDiggler/rpg-toolkit/tools/environments"
	gomock "go.uber.org/mock/gomock"
)

// MockEnvironmentGenerator is a mock of EnvironmentGenerator interface.
type MockEnvironmentGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockEnvironmentGeneratorMockRecorder
	isgomock struct{}
}

// MockEnvironmentGeneratorMockRecorder is the mock recorder for MockEnvironmentGenerator.
type MockEnvironmentGeneratorMockRecorder struct {
	mock *MockEnvironmentGenerator
}

// NewMockEnvironmentGenerator creates a new mock instance.
func NewMockEnvironmentGenerator(ctrl *gomock.Controller) *MockEnvironmentGenerator {
	mock := &MockEnvironmentGenerator{ctrl: ctrl}
	mock.recorder = &MockEnvironmentGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvironmentGenerator) EXPECT() *MockEnvironmentGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockEnvironmentGenerator) Generate(ctx context.Context, config environments.GenerationConfig) (environments.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, config)
	ret0, _ := ret[0].(environments.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockEnvironmentGeneratorMockRecorder) Generate(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockEnvironmentGenerator)(nil).Generate), ctx, config)
}

// GetCapabilities mocks base method.
func (m *MockEnvironmentGenerator) GetCapabilities() environments.GeneratorCapabilities {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCapabilities")
	ret0, _ := ret[0].(environments.GeneratorCapabilities)
	return ret0
}

// GetCapabilities indicates an expected call of GetCapabilities.
func (mr *MockEnvironmentGeneratorMockRecorder) GetCapabilities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCapabilities", reflect.TypeOf((*MockEnvironmentGenerator)(nil).GetCapabilities))
}

// GetGenerationType mocks base method.
func (m *MockEnvironmentGenerator) GetGenerationType() environments.GenerationType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenerationType")
	ret0, _ := ret[0].(environments.GenerationType)
	return ret0
}

// GetGenerationType indicates an expected call of GetGenerationType.
func (mr *MockEnvironmentGeneratorMockRecorder) GetGenerationType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenerationType", reflect.TypeOf((*MockEnvironmentGenerator)(nil).GetGenerationType))
}

// GetID mocks base method.
func (m *MockEnvironmentGenerator) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockEnvironmentGeneratorMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockEnvironmentGenerator)(nil).GetID))
}

// GetType mocks base method.
func (m *MockEnvironmentGenerator) GetType() core.EntityType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(core.EntityType)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockEnvironmentGeneratorMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockEnvironmentGenerator)(nil).GetType))
}

// Validate mocks base method.
func (m *MockEnvironmentGenerator) Validate(config environments.GenerationConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockEnvironmentGeneratorMockRecorder) Validate(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockEnvironmentGenerator)(nil).Validate), config)
}
