// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-toolkit/tools/environments (interfaces: QueryHandler)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_query_handler.go -package=mock github.com/KirkDiggler/rpg-toolkit/tools/environments QueryHandler
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	core "github.com/KirkDiggler/rpg-toolkit/core"
	environments "github.com/KirkDiggler/rpg-toolkit/tools/environments"
	spatial "github.com/KirkDiggler/rpg-toolkit/tools/spatial"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryHandler is a mock of QueryHandler interface.
type MockQueryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockQueryHandlerMockRecorder
	isgomock struct{}
}

// MockQueryHandlerMockRecorder is the mock recorder for MockQueryHandler.
type MockQueryHandlerMockRecorder struct {
	mock *MockQueryHandler
}

// NewMockQueryHandler creates a new mock instance.
func NewMockQueryHandler(ctrl *gomock.Controller) *MockQueryHandler {
	mock := &MockQueryHandler{ctrl: ctrl}
	mock.recorder = &MockQueryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryHandler) EXPECT() *MockQueryHandlerMockRecorder {
	return m.recorder
}

// HandleEntityQuery mocks base method.
func (m *MockQueryHandler) HandleEntityQuery(ctx context.Context, query environments.EntityQuery) ([]core.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleEntityQuery", ctx, query)
	ret0, _ := ret[0].([]core.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleEntityQuery indicates an expected call of HandleEntityQuery.
func (mr *MockQueryHandlerMockRecorder) HandleEntityQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEntityQuery", reflect.TypeOf((*MockQueryHandler)(nil).HandleEntityQuery), ctx, query)
}

// HandlePathQuery mocks base method.
func (m *MockQueryHandler) HandlePathQuery(ctx context.Context, query environments.PathQuery) ([]spatial.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePathQuery", ctx, query)
	ret0, _ := ret[0].([]spatial.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandlePathQuery indicates an expected call of HandlePathQuery.
func (mr *MockQueryHandlerMockRecorder) HandlePathQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePathQuery", reflect.TypeOf((*MockQueryHandler)(nil).HandlePathQuery), ctx, query)
}

// HandleRoomQuery mocks base method.
func (m *MockQueryHandler) HandleRoomQuery(ctx context.Context, query environments.RoomQuery) ([]spatial.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRoomQuery", ctx, query)
	ret0, _ := ret[0].([]spatial.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleRoomQuery indicates an expected call of HandleRoomQuery.
func (mr *MockQueryHandlerMockRecorder) HandleRoomQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRoomQuery", reflect.TypeOf((*MockQueryHandler)(nil).HandleRoomQuery), ctx, query)
}
