// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-toolkit/tools/environments (interfaces: Environment)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_environment.go -package=mock github.com/KirkDiggler/rpg-toolkit/tools/environments Environment
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	core "github.com/KirkDiggler/rpg-toolkit/core"
	environments "github.com/KirkDiggler/rpg-toolkit/tools/environments"
	spatial "github.com/KirkDiggler/rpg-toolkit/tools/spatial"
	gomock "go.uber.org/mock/gomock"
)

// MockEnvironment is a mock of Environment interface.
type MockEnvironment struct {
	ctrl     *gomock.Controller
	recorder *MockEnvironmentMockRecorder
	isgomock struct{}
}

// MockEnvironmentMockRecorder is the mock recorder for MockEnvironment.
type MockEnvironmentMockRecorder struct {
	mock *MockEnvironment
}

// NewMockEnvironment creates a new mock instance.
func NewMockEnvironment(ctrl *gomock.Controller) *MockEnvironment {
	mock := &MockEnvironment{ctrl: ctrl}
	mock.recorder = &MockEnvironmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvironment) EXPECT() *MockEnvironmentMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockEnvironment) Export() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockEnvironmentMockRecorder) Export() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockEnvironment)(nil).Export))
}

// FindPath mocks base method.
func (m *MockEnvironment) FindPath(from, to spatial.Position) ([]spatial.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPath", from, to)
	ret0, _ := ret[0].([]spatial.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPath indicates an expected call of FindPath.
func (mr *MockEnvironmentMockRecorder) FindPath(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPath", reflect.TypeOf((*MockEnvironment)(nil).FindPath), from, to)
}

// FindPathCube mocks base method.
func (m *MockEnvironment) FindPathCube(input *environments.FindPathCubeInput) (*environments.FindPathCubeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPathCube", input)
	ret0, _ := ret[0].(*environments.FindPathCubeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPathCube indicates an expected call of FindPathCube.
func (mr *MockEnvironmentMockRecorder) FindPathCube(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPathCube", reflect.TypeOf((*MockEnvironment)(nil).FindPathCube), input)
}

// GetConnection mocks base method.
func (m *MockEnvironment) GetConnection(connectionID string) (spatial.Connection, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", connectionID)
	ret0, _ := ret[0].(spatial.Connection)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockEnvironmentMockRecorder) GetConnection(connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockEnvironment)(nil).GetConnection), connectionID)
}

// GetConnections mocks base method.
func (m *MockEnvironment) GetConnections() []spatial.Connection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnections")
	ret0, _ := ret[0].([]spatial.Connection)
	return ret0
}

// GetConnections indicates an expected call of GetConnections.
func (mr *MockEnvironmentMockRecorder) GetConnections() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnections", reflect.TypeOf((*MockEnvironment)(nil).GetConnections))
}

// GetID mocks base method.
func (m *MockEnvironment) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockEnvironmentMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockEnvironment)(nil).GetID))
}

// GetMetadata mocks base method.
func (m *MockEnvironment) GetMetadata() environments.EnvironmentMetadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata")
	ret0, _ := ret[0].(environments.EnvironmentMetadata)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockEnvironmentMockRecorder) GetMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockEnvironment)(nil).GetMetadata))
}

// GetOrchestrator mocks base method.
func (m *MockEnvironment) GetOrchestrator() spatial.RoomOrchestrator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrchestrator")
	ret0, _ := ret[0].(spatial.RoomOrchestrator)
	return ret0
}

// GetOrchestrator indicates an expected call of GetOrchestrator.
func (mr *MockEnvironmentMockRecorder) GetOrchestrator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrchestrator", reflect.TypeOf((*MockEnvironment)(nil).GetOrchestrator))
}

// GetRoom mocks base method.
func (m *MockEnvironment) GetRoom(roomID string) (spatial.Room, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", roomID)
	ret0, _ := ret[0].(spatial.Room)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockEnvironmentMockRecorder) GetRoom(roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockEnvironment)(nil).GetRoom), roomID)
}

// GetRooms mocks base method.
func (m *MockEnvironment) GetRooms() []spatial.Room {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRooms")
	ret0, _ := ret[0].([]spatial.Room)
	return ret0
}

// GetRooms indicates an expected call of GetRooms.
func (mr *MockEnvironmentMockRecorder) GetRooms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRooms", reflect.TypeOf((*MockEnvironment)(nil).GetRooms))
}

// GetTheme mocks base method.
func (m *MockEnvironment) GetTheme() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockEnvironmentMockRecorder) GetTheme() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockEnvironment)(nil).GetTheme))
}

// GetType mocks base method.
func (m *MockEnvironment) GetType() core.EntityType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(core.EntityType)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockEnvironmentMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockEnvironment)(nil).GetType))
}

// QueryEntities mocks base method.
func (m *MockEnvironment) QueryEntities(ctx context.Context, query environments.EntityQuery) ([]core.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryEntities", ctx, query)
	ret0, _ := ret[0].([]core.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryEntities indicates an expected call of QueryEntities.
func (mr *MockEnvironmentMockRecorder) QueryEntities(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryEntities", reflect.TypeOf((*MockEnvironment)(nil).QueryEntities), ctx, query)
}

// QueryRooms mocks base method.
func (m *MockEnvironment) QueryRooms(ctx context.Context, query environments.RoomQuery) ([]spatial.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryRooms", ctx, query)
	ret0, _ := ret[0].([]spatial.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRooms indicates an expected call of QueryRooms.
func (mr *MockEnvironmentMockRecorder) QueryRooms(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRooms", reflect.TypeOf((*MockEnvironment)(nil).QueryRooms), ctx, query)
}
