// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-toolkit/tools/environments (interfaces: RoomBuilder)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_room_builder.go -package=mock github.com/KirkDiggler/rpg-toolkit/tools/environments RoomBuilder
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	environments "github.com/KirkDiggler/rpg-toolkit/tools/environments"
	spatial "github.com/KirkDiggler/rpg-toolkit/tools/spatial"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomBuilder is a mock of RoomBuilder interface.
type MockRoomBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockRoomBuilderMockRecorder
	isgomock struct{}
}

// MockRoomBuilderMockRecorder is the mock recorder for MockRoomBuilder.
type MockRoomBuilderMockRecorder struct {
	mock *MockRoomBuilder
}

// NewMockRoomBuilder creates a new mock instance.
func NewMockRoomBuilder(ctrl *gomock.Controller) *MockRoomBuilder {
	mock := &MockRoomBuilder{ctrl: ctrl}
	mock.recorder = &MockRoomBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomBuilder) EXPECT() *MockRoomBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockRoomBuilder) Build() (spatial.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build")
	ret0, _ := ret[0].(spatial.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockRoomBuilderMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockRoomBuilder)(nil).Build))
}

// WithDestructibleRatio mocks base method.
func (m *MockRoomBuilder) WithDestructibleRatio(ratio float64) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDestructibleRatio", ratio)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithDestructibleRatio indicates an expected call of WithDestructibleRatio.
func (mr *MockRoomBuilderMockRecorder) WithDestructibleRatio(ratio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDestructibleRatio", reflect.TypeOf((*MockRoomBuilder)(nil).WithDestructibleRatio), ratio)
}

// WithFeatures mocks base method.
func (m *MockRoomBuilder) WithFeatures(features ...environments.Feature) environments.RoomBuilder {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range features {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithFeatures", varargs...)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithFeatures indicates an expected call of WithFeatures.
func (mr *MockRoomBuilderMockRecorder) WithFeatures(features ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithFeatures", reflect.TypeOf((*MockRoomBuilder)(nil).WithFeatures), features...)
}

// WithLayout mocks base method.
func (m *MockRoomBuilder) WithLayout(layout environments.Layout) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLayout", layout)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithLayout indicates an expected call of WithLayout.
func (mr *MockRoomBuilderMockRecorder) WithLayout(layout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLayout", reflect.TypeOf((*MockRoomBuilder)(nil).WithLayout), layout)
}

// WithMaterial mocks base method.
func (m *MockRoomBuilder) WithMaterial(material string) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithMaterial", material)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithMaterial indicates an expected call of WithMaterial.
func (mr *MockRoomBuilderMockRecorder) WithMaterial(material any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithMaterial", reflect.TypeOf((*MockRoomBuilder)(nil).WithMaterial), material)
}

// WithPrefab mocks base method.
func (m *MockRoomBuilder) WithPrefab(prefab environments.RoomPrefab) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithPrefab", prefab)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithPrefab indicates an expected call of WithPrefab.
func (mr *MockRoomBuilderMockRecorder) WithPrefab(prefab any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithPrefab", reflect.TypeOf((*MockRoomBuilder)(nil).WithPrefab), prefab)
}

// WithRandomSeed mocks base method.
func (m *MockRoomBuilder) WithRandomSeed(seed int64) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithRandomSeed", seed)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithRandomSeed indicates an expected call of WithRandomSeed.
func (mr *MockRoomBuilderMockRecorder) WithRandomSeed(seed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithRandomSeed", reflect.TypeOf((*MockRoomBuilder)(nil).WithRandomSeed), seed)
}

// WithSafety mocks base method.
func (m *MockRoomBuilder) WithSafety(safety environments.PathSafetyParams) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithSafety", safety)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithSafety indicates an expected call of WithSafety.
func (mr *MockRoomBuilderMockRecorder) WithSafety(safety any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSafety", reflect.TypeOf((*MockRoomBuilder)(nil).WithSafety), safety)
}

// WithShape mocks base method.
func (m *MockRoomBuilder) WithShape(shapeName string) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithShape", shapeName)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithShape indicates an expected call of WithShape.
func (mr *MockRoomBuilderMockRecorder) WithShape(shapeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithShape", reflect.TypeOf((*MockRoomBuilder)(nil).WithShape), shapeName)
}

// WithSize mocks base method.
func (m *MockRoomBuilder) WithSize(width, height int) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithSize", width, height)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithSize indicates an expected call of WithSize.
func (mr *MockRoomBuilderMockRecorder) WithSize(width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSize", reflect.TypeOf((*MockRoomBuilder)(nil).WithSize), width, height)
}

// WithTheme mocks base method.
func (m *MockRoomBuilder) WithTheme(theme string) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTheme", theme)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithTheme indicates an expected call of WithTheme.
func (mr *MockRoomBuilderMockRecorder) WithTheme(theme any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTheme", reflect.TypeOf((*MockRoomBuilder)(nil).WithTheme), theme)
}

// WithWallDensity mocks base method.
func (m *MockRoomBuilder) WithWallDensity(density float64) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithWallDensity", density)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithWallDensity indicates an expected call of WithWallDensity.
func (mr *MockRoomBuilderMockRecorder) WithWallDensity(density any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithWallDensity", reflect.TypeOf((*MockRoomBuilder)(nil).WithWallDensity), density)
}

// WithWallPattern mocks base method.
func (m *MockRoomBuilder) WithWallPattern(pattern string) environments.RoomBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithWallPattern", pattern)
	ret0, _ := ret[0].(environments.RoomBuilder)
	return ret0
}

// WithWallPattern indicates an expected call of WithWallPattern.
func (mr *MockRoomBuilderMockRecorder) WithWallPattern(pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithWallPattern", reflect.TypeOf((*MockRoomBuilder)(nil).WithWallPattern), pattern)
}
