// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-toolkit/rulebooks/dnd5e/combat (interfaces: Combatant,CombatantLookup)
//
// Generated by this command:
//
//	mockgen -destination=combat/mock/mock_combatant.go -package=mock_combat github.com/KirkDiggler/rpg-toolkit/rulebooks/dnd5e/combat Combatant,CombatantLookup
//

// Package mock_combat is a generated GoMock package.
package mock_combat

import (
	context "context"
	reflect "reflect"

	combat "github.com/KirkDiggler/rpg-toolkit/rulebooks/dnd5e/combat"
	shared "github.com/KirkDiggler/rpg-toolkit/rulebooks/dnd5e/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockCombatant is a mock of Combatant interface.
type MockCombatant struct {
	ctrl     *gomock.Controller
	recorder *MockCombatantMockRecorder
	isgomock struct{}
}

// MockCombatantMockRecorder is the mock recorder for MockCombatant.
type MockCombatantMockRecorder struct {
	mock *MockCombatant
}

// NewMockCombatant creates a new mock instance.
func NewMockCombatant(ctrl *gomock.Controller) *MockCombatant {
	mock := &MockCombatant{ctrl: ctrl}
	mock.recorder = &MockCombatantMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCombatant) EXPECT() *MockCombatantMockRecorder {
	return m.recorder
}

// AC mocks base method.
func (m *MockCombatant) AC() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AC")
	ret0, _ := ret[0].(int)
	return ret0
}

// AC indicates an expected call of AC.
func (mr *MockCombatantMockRecorder) AC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AC", reflect.TypeOf((*MockCombatant)(nil).AC))
}

// AbilityScores mocks base method.
func (m *MockCombatant) AbilityScores() shared.AbilityScores {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbilityScores")
	ret0, _ := ret[0].(shared.AbilityScores)
	return ret0
}

// AbilityScores indicates an expected call of AbilityScores.
func (mr *MockCombatantMockRecorder) AbilityScores() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbilityScores", reflect.TypeOf((*MockCombatant)(nil).AbilityScores))
}

// ApplyDamage mocks base method.
func (m *MockCombatant) ApplyDamage(ctx context.Context, input *combat.ApplyDamageInput) *combat.ApplyDamageResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDamage", ctx, input)
	ret0, _ := ret[0].(*combat.ApplyDamageResult)
	return ret0
}

// ApplyDamage indicates an expected call of ApplyDamage.
func (mr *MockCombatantMockRecorder) ApplyDamage(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDamage", reflect.TypeOf((*MockCombatant)(nil).ApplyDamage), ctx, input)
}

// GetHitPoints mocks base method.
func (m *MockCombatant) GetHitPoints() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHitPoints")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetHitPoints indicates an expected call of GetHitPoints.
func (mr *MockCombatantMockRecorder) GetHitPoints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHitPoints", reflect.TypeOf((*MockCombatant)(nil).GetHitPoints))
}

// GetID mocks base method.
func (m *MockCombatant) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockCombatantMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockCombatant)(nil).GetID))
}

// GetMaxHitPoints mocks base method.
func (m *MockCombatant) GetMaxHitPoints() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxHitPoints")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMaxHitPoints indicates an expected call of GetMaxHitPoints.
func (mr *MockCombatantMockRecorder) GetMaxHitPoints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxHitPoints", reflect.TypeOf((*MockCombatant)(nil).GetMaxHitPoints))
}

// IsDirty mocks base method.
func (m *MockCombatant) IsDirty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDirty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDirty indicates an expected call of IsDirty.
func (mr *MockCombatantMockRecorder) IsDirty() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDirty", reflect.TypeOf((*MockCombatant)(nil).IsDirty))
}

// MarkClean mocks base method.
func (m *MockCombatant) MarkClean() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkClean")
}

// MarkClean indicates an expected call of MarkClean.
func (mr *MockCombatantMockRecorder) MarkClean() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkClean", reflect.TypeOf((*MockCombatant)(nil).MarkClean))
}

// ProficiencyBonus mocks base method.
func (m *MockCombatant) ProficiencyBonus() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProficiencyBonus")
	ret0, _ := ret[0].(int)
	return ret0
}

// ProficiencyBonus indicates an expected call of ProficiencyBonus.
func (mr *MockCombatantMockRecorder) ProficiencyBonus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProficiencyBonus", reflect.TypeOf((*MockCombatant)(nil).ProficiencyBonus))
}

// MockCombatantLookup is a mock of CombatantLookup interface.
type MockCombatantLookup struct {
	ctrl     *gomock.Controller
	recorder *MockCombatantLookupMockRecorder
	isgomock struct{}
}

// MockCombatantLookupMockRecorder is the mock recorder for MockCombatantLookup.
type MockCombatantLookupMockRecorder struct {
	mock *MockCombatantLookup
}

// NewMockCombatantLookup creates a new mock instance.
func NewMockCombatantLookup(ctrl *gomock.Controller) *MockCombatantLookup {
	mock := &MockCombatantLookup{ctrl: ctrl}
	mock.recorder = &MockCombatantLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCombatantLookup) EXPECT() *MockCombatantLookupMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCombatantLookup) Get(id string) (combat.Combatant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(combat.Combatant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCombatantLookupMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCombatantLookup)(nil).Get), id)
}
