name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
    
    - name: Run golangci-lint
      working-directory: ./core
      run: golangci-lint run --no-config ./...
    
    - name: Run tests
      working-directory: ./core
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Check test coverage
      working-directory: ./core
      run: |
        go tool cover -func=coverage.txt
        # Ensure 100% coverage for core module
        coverage=$(go tool cover -func=coverage.txt | grep total | awk '{print $3}' | sed 's/%//')
        if (( $(echo "$coverage < 100" | bc -l) )); then
          echo "Test coverage is below 100% (current: $coverage%)"
          exit 1
        fi
        echo "Test coverage: $coverage%"
    
    - name: Run go mod tidy
      working-directory: ./core
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum || (echo "Please run 'go mod tidy'" && exit 1)