name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install tools
      run: make install-tools
    
    - name: Run linter on all modules
      run: make lint-all
    
    - name: Run tests on all modules
      run: make test-all
    
    - name: Check go mod tidy on all modules
      run: |
        # Run go mod tidy on all modules
        find . -name "go.mod" -type f -not -path "./vendor/*" | while read -r modfile; do
          dir=$(dirname "$modfile")
          echo "→ Tidying $dir..."
          (cd "$dir" && go mod tidy) || exit 1
        done
        git diff --exit-code || (echo "Please run 'go mod tidy' on all modules" && exit 1)